apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudpose-deployment
  namespace: yanuoz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudpose
  template:
    metadata:
      labels:
        app: cloudpose
    spec:
      containers:
        - name: cloudpose-container
          image: yanuoz/cloudpose-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 60001
          resources:
            requests:
              memory: "1024Mi"
              cpu: "0.5"
            limits:
              memory: "1024Mi"
              cpu: "0.5"          
