apiVersion: v1
kind: Service
metadata:
  namespace: yanuoz
  name: cloudpose-service
spec:
  type: NodePort
  selector:
    app: cloudpose
  ports:
    - name: http
      port: 60001
      targetPort: 60001
      nodePort: 30001